### ISSUE TITLE
Websites aren't blocked in Google Image Search

### ISSUE THREAD

**Issue by 21720m** [iorate/ublacklist#476]
## Expected Behavior
Blocked websites not to be seen in google image search.

## Actual Behavior
The websites still appear, even though they don't in text search.

## Steps to Reproduce the Problem
1. Block a website.
2. Search it up through normal text and through google images.
3. Compare.

## Specifications

- Browser: Firefox
- Other extensions/add-ons: uBlock Origin, Dark Reader.

- Search engine: Google
- Language: Dutch
- Region: The Netherlands

I attached an image. OpenArt AI and Prompt Hunt (I think StarryAI as well but I'm not sure) are supposed to be blocked. 
![Screenshot_20240525_161814_Firefox](https://github.com/iorate/ublacklist/assets/170813329/2a728a6f-6b0c-4405-9eb2-487e01fa71c8)

**Comment by aug-dev** [comment]
Hey there!

What version of Google are you using? (Mobile or Desktop)

From the screenshot it looks like it is mobile, but it is worth asking.

**Comment by 21720m** [comment]
Hi! It's indeed the mobile version. I just tried searching the same
sentence on my laptop with the same settings and there it works just fine,
so it seems to be just the mobile version.

Op za 25 mei 2024 22:42 schreef Pedro Augusto ***@***.***>:

**Comment by tommaniacal** [comment]
I'm also having this issue, Firefox Android version, blocked sites show on both the image search and the image/video results on top of the regular google search page

**Comment by aug-dev** [comment]
Fixed :)

**Comment by aug-dev** [comment]
> I'm also having this issue, Firefox Android version, blocked sites show on both the image search and the image/video results on top of the regular google search page

@tommaniacal Hey there! The images/videos on not being blocked on the main page (not on the image/videos section) is a separate but known issue.

This is probably what I'm going to fix next.

**Comment by 21720m** [comment]
Hi!

For me nothing has changed, I still see the websites I blacklisted in the
image search. Am I supposed to update something? I've turned the extension
off and back on again, and I tried to see if any of my other extensions
were interfering, but they aren't. When I view the site in desktop mode it
does work, so it's specifically just the mobile view. I'm not sure what
else to try, I'm not very tech savvy I'm sorry

Op do 6 jun. 2024 16:30 schreef Pedro Augusto ***@***.***>:

**Comment by aug-dev** [comment]
Oh, sorry, I think I should've been clearer with my comment.

The problem has been fixed, but it's only going to be released in the next version of uBlacklist.

I'm still new to this project, but from what I can understand it seems that a new version comes out once a month (this is not a strict rule).

Maybe we could increase the speed at which we push these bug fixes to users, but this is probably something that @iorate has more experience with than I have.

Anyways, once the new version is released, the problem should be solved. :)

**Comment by 21720m** [comment]
Ohh I see, sorry I didn't know that! Thank you for clarifying

Op do 6 jun. 2024 23:34 schreef Pedro Augusto ***@***.***>:
