### ISSUE TITLE
Invisible all search results in Ecosia

### ISSUE THREAD

**Issue by komkom8203** [iorate/ublacklist#487]
For a few days, all search results have been invisible in Ecosia with using uBlacklist.
There is no problem that "Preferred search provider" in Ecosia's settings is "Bing", but the problem is occured while the setting is "No preference" or "Google".
I think this problem doesn't depend on specific platform because this problem is occured in Firefox for WIndows, Vivaldi for Windows and Firefox for Android those are my all environment.
By Ecosia's behaviour, I think this problem's cause is Ecosia's specification changes.

In Vivaldi
![スクリーンショット 2024-06-11 212413](https://github.com/iorate/ublacklist/assets/172390428/71495fa0-35eb-4af3-be24-02d7d8b37668)

In Firefox for PC
![スクリーンショット 2024-06-11 212344](https://github.com/iorate/ublacklist/assets/172390428/322fb114-1b0c-49b4-bdda-9748af4577a4)

In Firefox for Android
![Screenshot_20240611_212513_Firefox Nightly](https://github.com/iorate/ublacklist/assets/172390428/321ddef9-3806-47f7-872d-f6c59f6b07c2)

uBlacklist Version: 8.7.0(Firefox), 8.7.1(Vivaldi)
Browsers and OS: 
Firefox 127.0b9(64bit) in Windows11
Firefox 128.0a1 in Android14
Vivlaldi 6.7.3329.35(64bit) in Windows11

*I am Japanese person, so my writing English may be wrong some. (Some sentence is used DeepL translation.)

**Comment by komkom8203** [comment]
Sorry for the delay, but I checked the operation today with version 8.8.1 and confirmed that the above problem has been resolved.
Thank you for fixing quickly!

**Comment by nickavem** [comment]
I still get this issue intermittently with 8.9.1. On iOS, it happens every time.
